### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by meetsudhirg** [TimeWith/twitter-followers-fetcher#1]
File "run.py", line 55
    print 'Getting Twitter data for account: {}'.format(handler)
                                               ^
SyntaxError: invalid syntax

**Comment by agouil** [comment]
It seems you're running the script with Python 3, while this project is written in Python 2. I'm planning to start supporting Python 3 too but I don't have a fixed date of releasing these changes yet.
A quick solution is to try running the script with Python 2. Furthermore, I'd be more than happy to point you to the right direction if you're willing to make the changes for supporting both Python versions.
